# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [117]:
# Your code goes here
import pandas as pd
import numpy as np

url_1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
url_2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url_3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

df1 = pd.read_csv(url_1)
df2 = pd.read_csv(url_2)
df3 = pd.read_csv(url_3)

In [118]:
print (df1.shape[0])
print (df2.shape[0])
print (df3.shape[0])

4008
996
7070

In [121]:
# df = pd.concat([df1, df2, df3], axis=0)
new_cols = {'st': 'state'} 
for df in df_list:       
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
    # df = df.rename(columns= new_cols)
# df_list = list(df.rename(columns= new_cols) for df in df_list)    
df1 = df1.rename(columns= new_cols)
df2 = df2.rename(columns= new_cols)
df3 = df3.rename(columns= new_cols)
df_list = [df1, df2, df3]

In [122]:
print(df1.columns)
print(df2.columns)
print(df3.columns)

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')
Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'total_claim_amount', 'policy_type', 'vehicle_class'],
      dtype='object')
Index(['customer', 'state', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='object')

In [123]:
df_all= pd.concat(df_list, axis=0)
df_all#.info()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,M,Bachelor,23405.98798,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
7066,PK87824,California,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
7067,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
7068,UP19263,California,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
7069,Y167826,California,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [ ]:
df_all["customer_lifetime_value"].value_counts()

In [142]:
def clean_State(x):
    '''Replace abbreviation with full name'''
    match x:
        case "Cali":
            return "California"
        case "WA":
            return "Washington"
        case "AZ":
            return "Arizona"
        case _:
            return x

def clean_Gender(x):
    match x:
        case "Femal":
            return "F"
        case "Male":
            return "M"
        case "Femal":
            return "F"
        case _:
            return x
def clean_CTV(x):
    # if x != None:
        x = str(x)
        if x.endswith("%"):
            # return float(x_str[0:len(x)-1])
            # return float(x_str.str.replace(r"-\%", "", regex=True))
            return float(x.replace("%", ""))

        else:
            return x
    # else:
    #     return x
df2 = df_all.copy()        
df2["state"] = df2["state"].apply(clean_State)
df2["gender"] = df2["gender"].apply(clean_Gender)
df2["education"] = df2["education"].apply(lambda x: "Bachelor" if x == "Bachelors" else x)
df2["vehicle_class"] = df2["vehicle_class"].apply(lambda x: "Luxury" if x in ["Sports Car", "Luxury SUV", "Luxury Car"] else x) 
df2["customer_lifetime_value"] = df2["customer_lifetime_value"].apply(clean_CTV)

In [137]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12074 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9015 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    12074 non-null  object
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [143]:
df3 = df2.copy()
df3=df3.dropna(how="all",subset=["income", "monthly_premium_auto", "number_of_open_complaints", "total_claim_amount"]).dropna(subset ="customer")
# df3["gender"] = df3["gender"].fillna(df3["gender"].mode().values[0])
df3["gender"] = df3["gender"].ffill().bfill()
 # df3["state"] = df3["state"].fillna(df3["state"].mode().values[0])

In [145]:
df3.tail()
# df3.info()

# df3.isna().sum()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
7065,LA72316,California,M,Bachelor,23405.98798,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
7066,PK87824,California,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
7067,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
7068,UP19263,California,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
7069,Y167826,California,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [146]:
# Your code goes here
url_ = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"
customer_df = pd.read_csv(url_)

In [151]:
customer_df.head()
# customer_df.isna().sum()
# customer_df.columns
#

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [168]:
customer_df.pivot_table(index="sales_channel", values="total_claim_amount", aggfunc='sum')

               total_claim_amount
sales_channel
Agent                1.810227e+06
Branch               1.301204e+06
Call Center          9.266008e+05
Web                  7.066000e+05

In [169]:
customer_df.pivot_table(index="sales_channel",  values="monthly_premium_auto", aggfunc='sum')

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [167]:
# pivoted = customer_df.set_index(["gender", "education"])
# pivoted.pivot_table(index= pivoted.index, columns="sales_channel", values="customer_lifetime_value", aggfunc=["std","mean"])
pd.pivot_table(customer_df, values='customer_lifetime_value', index=['gender', 'education'], aggfunc='mean')

                             customer_lifetime_value
gender education
F      Bachelor                          7874.269478
       College                           7748.823325
       Doctor                            7328.508916
       High School or Below              8675.220201
       Master                            8157.053154
M      Bachelor                          7703.601675
       College                           8052.459288
       Doctor                            7415.333638
       High School or Below              8149.687783
       Master                            8168.832659

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here